# Configuration file for Sphinx documentation builder.
# https://www.sphinx-doc.org/en/master/usage/configuration.html

import os
import sys
from pathlib import Path

# -- Path setup --------------------------------------------------------------
# Add project root to sys.path for autodoc
sys.path.insert(0, str(Path(__file__).parent.parent.parent / "src"))

# -- Project information -----------------------------------------------------
project = "Lactuca"
copyright = "2026, Alberto Aragoneses"
author = "Alberto Aragoneses"

# Version from pyproject.toml (dynamic)
try:
    from importlib.metadata import version

    release = version("lactuca")
except Exception:
    import tomllib

    pyproject = Path(__file__).parent.parent.parent / "pyproject.toml"
    with open(pyproject, "rb") as f:
        release = tomllib.load(f)["project"]["version"]

version = release  # Short version (e.g., 0.0.1)

# -- General configuration ---------------------------------------------------
extensions = [
    "sphinx.ext.autodoc",  # Auto-generate from docstrings
    "sphinx.ext.autosummary",  # Summary tables for inherited members
    "sphinx.ext.napoleon",  # NumPy/Google docstring support
    # sphinx.ext.viewcode intentionally omitted: source files are compiled
    # and must not be exposed in public documentation.
    "sphinx.ext.intersphinx",  # Links to other projects
    "sphinx.ext.mathjax",  # LaTeX math via MathJax
    # "sphinx_autodoc_typehints",  # DISABLED - testing duplicate warnings
    "sphinx_copybutton",  # Copy code button
    "myst_parser",  # Markdown support
    "sphinx_design",  # Cards, tabs, grids
]

# MyST configuration (Markdown support)
myst_enable_extensions = [
    "colon_fence",  # ::: directive
    "deflist",  # Definition lists
    "fieldlist",  # Field lists
    "attrs_inline",  # {.class} syntax
    "substitution",  # {{ variable }}
    "dollarmath",  # $...$ and $$...$$ math blocks
]

# Napoleon settings (NumPy docstrings)
napoleon_google_docstring = False
napoleon_numpy_docstring = True
napoleon_use_param = True
napoleon_use_rtype = True

# Autodoc settings
autodoc_typehints = "signature"  # Show in signature, not description
autodoc_member_order = "groupwise"

# Autosummary settings
autosummary_generate = False  # Do not generate stub pages; links resolve to autoclass pages

# Templates path
templates_path = ["_templates"]

# Exclude patterns
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# Suppress myst.header: changelog.md is auto-generated by git-cliff, not editable.
suppress_warnings = ["myst.header"]

# -- Options for HTML output -------------------------------------------------
html_theme = "pydata_sphinx_theme"

html_theme_options = {
    "logo": {
        "text": project,
    },
    "github_url": "https://github.com/actuaan/lactuca",
    "collapse_navigation": True,
    "header_links_before_dropdown": 6,
    # --- CONFIGURACIÓN DE COLORES DE CÓDIGO ---
    # Opción A (Estilo GitHub): Muy limpio y familiar
    # "pygments_light_style": "github-light",
    # "pygments_dark_style": "github-dark",
    # Opción B (Clásico equilibrado):
    "pygments_light_style": "tango",
    "pygments_dark_style": "material",
    # ------------------------------------------
    "navbar_end": [
        # "version-switcher",  # Comentado para desarrollo local (funciona en CI/CD)
        "search-button.html",
        "theme-switcher.html",
        "navbar-icon-links.html",
    ],
    "navbar_persistent": [],
    "show_nav_level": 2,
    "show_toc_level": 2,
    # Version switcher configuration (like NumPy docs)
    "switcher": {
        # En local usa path relativo, en CI usa URL absoluta
        "json_url": os.getenv(
            "SPHINX_VERSIONS_JSON_URL",
            "_static/versions.json",  # Path a _static para desarrollo local
        ),
        "version_match": os.getenv("SPHINX_VERSION_MATCH", version),
    },
}

html_title = f"{project} {version}"
html_static_path = ["_static"]
html_css_files = ["custom.css"]  # Custom CSS with Open Sans and Lato fonts
html_context = {"default_mode": "light"}

# -- Source-code protection --------------------------------------------------
# Prevent any form of source-code exposure in the published documentation.
# All .py files are compiled; neither Python source nor doc source should
# be reachable via the generated HTML site.
html_show_sourcelink = False  # Hide "Show page source" link in the UI
html_copy_source = False  # Do NOT copy .md/.rst files to _sources/ in the build
# output — prevents direct URL access to doc sources on
# GitHub Pages even when the UI link is hidden.
# sphinx.ext.viewcode is intentionally absent from extensions (see above).

html_logo = "_static/lactuca_logo.svg"
html_favicon = "_static/lactuca_logo.svg"

# -- Options for MathJax (LaTeX math) ----------------------------------------
# MathJax configuration for actuarial notation with custom macros
mathjax3_config = {
    "tex": {
        "inlineMath": [["$", "$"], ["\\(", "\\)"]],
        "displayMath": [["$$", "$$"], ["\\[", "\\]"]],
        "packages": {
            "[]": ["base", "ams", "newcommand", "configmacros"],
            "[+]": ["physics"],
        },
        "macros": {
            # Actuarial macros for Lactuca (standard life contingencies notation)
            # Survival and mortality probabilities
            "px": ["{}_{#1}p_{#2}", 2],  # n-year survival prob
            "qx": ["{}_{#1}q_{#2}", 2],  # n-year death prob
            "tpx": ["{}_{#1}p_{#2}^{\\tau}", 2],  # Temporary survival
            "tqx": ["{}_{#1}q_{#2}^{\\tau}", 2],  # Temporary mortality
            # Life annuities (discrete)
            "ax": ["\\ddot{a}_{\\overline{#1}|}", 1],  # Annuity due (whole life)
            "axi": ["\\ddot{a}_{#1}^{(#2)}", 2],  # m-thly annuity (whole life)
            "nax": ["\\ddot{a}_{#1:\\overline{#2}|}", 2],  # Temporary annuity due
            "naxi": ["\\ddot{a}_{#1:\\overline{#2}|}^{(#3)}", 3],  # Temporary m-thly
            # Life annuities (continuous)
            "abarc": ["\\bar{a}_{#1}", 1],  # Continuous annuity (whole life)
            "nabarc": ["\\bar{a}_{#1:\\overline{#2}|}", 2],  # Temporary continuous
            # Accumulated values
            "sx": ["\\ddot{s}_{\\overline{#1}|}", 1],  # Accumulated value annuity due
            "sxi": ["\\ddot{s}_{#1}^{(#2)}", 2],  # m-thly accumulated
            # Life insurances
            "Ax": ["A_{#1}", 1],  # Whole life insurance (discrete)
            "Axc": ["\\bar{A}_{#1}", 1],  # Whole life continuous
            "nAx": ["A_{#1:\\overline{#2}|}", 2],  # Term insurance
            "nEx": ["{}_{#1}E_{#2}", 2],  # Pure endowment
            # Commutation functions
            "Dx": ["D_{#1}", 1],
            "Nx": ["N_{#1}", 1],
            "Sx": ["S_{#1}", 1],
            "Cx": ["C_{#1}", 1],
            "Mx": ["M_{#1}", 1],
            "Rx": ["R_{#1}", 1],
            # Life expectancy
            "ex": ["\\mathring{e}_{#1}", 1],  # Complete life expectancy
            "edotx": ["\\ddot{e}_{#1}", 1],  # Curtate life expectancy
            # Interest and discount factors
            "vx": ["v^{#1}", 1],  # Discount factor
            "vn": ["v^{#1}", 1],  # n-year discount
            "dx": ["d^{(#1)}", 1],  # m-thly discount rate
            "ix": ["i^{(#1)}", 1],  # m-thly interest rate
            # Joint life and last survivor
            "pxy": ["p_{#1#2}", 2],  # Joint survival
            "qxy": ["q_{#1#2}", 2],  # Joint death
            "axy": ["\\ddot{a}_{#1#2}", 2],  # Joint annuity
            "axybar": ["\\ddot{a}_{\\overline{#1#2}}", 2],  # Last survivor annuity
        },
    },
    "options": {
        "skipHtmlTags": ["script", "noscript", "style", "textarea", "pre", "code"],
    },
    "loader": {
        "load": ["[tex]/physics", "[tex]/ams"],
    },
}

mathjax_path = "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"

# -- Intersphinx mapping -----------------------------------------------------
# No intersphinx cross-references are currently used in the docs.
# Add entries here only when Sphinx roles (:class:, :func:, etc.) referencing
# external inventories are actually introduced.
intersphinx_mapping: dict = {}

# -- sphinx-multiversion Configuration ----------------------------------------
# Similar to mike in MkDocs
smv_tag_whitelist = r"^v\d+\.\d+\.\d+$"  # Only semantic version tags
smv_branch_whitelist = r"^(main|stable)$"  # Branches to document
smv_remote_whitelist = r"^(origin)$"  # Allowed remote
smv_released_pattern = r"^tags/v.*$"  # Release pattern
smv_outputdir_format = "{ref.name}"  # Directory structure

# Version banner settings
smv_latest_version = "latest"  # Alias for latest version
smv_prefer_remote_refs = False  # Use local refs first


def setup(app):
    """Suppress spurious duplicate-object warnings from re-exported class hierarchies.

    LifeTable, DisabilityTable, ExitTable, and TableBuilder are defined in
    lactuca.tables.* sub-modules but re-exported at the lactuca.* level.
    Sphinx 9.x re-registers their method descriptors after the read phase
    (docname = <unknown>), producing spurious 'duplicate object description'
    warnings that cannot be caught via suppress_warnings (no type= code).
    """
    import logging as _logging

    import sphinx.domains.python as _spd

    _KNOWN_CLASSES = frozenset(  # noqa: N806
        [
            "lactuca.LifeTable",
            "lactuca.DisabilityTable",
            "lactuca.ExitTable",
            "lactuca.TableBuilder",
        ]
    )

    class _SuppressKnownDuplicates(_logging.Filter):
        def filter(self, record):
            msg = record.getMessage()
            if "duplicate object description" not in msg:
                return True
            return not any(cls + "." in msg for cls in _KNOWN_CLASSES)

    # Sphinx prepends "sphinx." to all logger names, so the underlying
    # Python logger is "sphinx.sphinx.domains.python", not "sphinx.domains.python".
    _spd.logger.logger.addFilter(_SuppressKnownDuplicates())
